/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// kws20
// This file was @generated by ai8xize.py --device MAX78000 --board-name FTHR_Max78000 --config-file networks/kws20_64_copy.yaml --checkpoint-file ../ai8x-training/logs/2026.05.14-170835/qat_best-q.pth.tar --prefix kws20 --test-dir kws20_64_c_code

// DO NOT EDIT - regenerate this file instead!

// Configuring 11 layers
// Input data: HWC
// Layer 0: 128x128, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 96x128 output
// Layer 1: 96x128, max pool 2 with stride 2, conv1d with kernel size 3, stride 1, pad 0, ReLU, 96x62 output
// Layer 2: 96x62, no pooling, conv1d with kernel size 3, stride 1, pad 0, no activation, 64x60 output
// Layer 3: 96x62, no pooling, conv1d with kernel size 3, stride 1, pad 0, no activation, 64x60 output
// Layer 4: 2x64x60x1, no pooling, 2-element add, no convolution, 64x60x1 output
// Layer 5: 64x60, no pooling, conv1d with kernel size 3, stride 1, pad 0, ReLU, 48x58 output
// Layer 6: 48x58, max pool 2 with stride 2, conv1d with kernel size 3, stride 1, pad 0, ReLU, 64x27 output
// Layer 7: 64x27, no pooling, conv1d with kernel size 3, stride 1, pad 0, ReLU, 96x25 output
// Layer 8: 96x25, avg pool 2 with stride 2, conv1d with kernel size 3, stride 1, pad 0, ReLU, 96x10 output
// Layer 9: 96x10, max pool 2 with stride 2, conv1d with kernel size 3, stride 1, pad 0, ReLU, 64x3 output
// Layer 10: 64x3x1 flattened to 192x1x1, no pooling, linear, no activation, 21x1x1 output

// Final Scales: {0: 0, 1: 0, 2: 0, 3: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 5}

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

#define CNN_INFERENCE_TIMER MXC_TMR0

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

int cnn_load_bias(void)
{
  // Not used in this network
  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x0000000a; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x0000000a; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x0000000a; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x0000000a; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50100310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50100590) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x000005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50100790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50500310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50500590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x000005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50500790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50900310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50900590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x000005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50900790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900710) = 0xffffffff; // Mask and processor enables

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50d00310) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00490) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x000005f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00110) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d00790) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00710) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50100194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50100514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x00006ba0; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x07800d78; // Mask offset and count
  *((volatile uint32_t *) 0x50100114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50500194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50500514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x07800d78; // Mask offset and count
  *((volatile uint32_t *) 0x50500114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50500794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50900194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50900514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x07800d78; // Mask offset and count
  *((volatile uint32_t *) 0x50900114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50900794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x0000007f; // Rows
  *((volatile uint32_t *) 0x50d00194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00494) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d00514) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x07800d78; // Mask offset and count
  *((volatile uint32_t *) 0x50d00114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d00794) = 0x00022000; // Post processing register

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50100318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100598) = 0x00006920; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x0d801178; // Mask offset and count
  *((volatile uint32_t *) 0x50100118) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100798) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50500318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500598) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x0d801178; // Mask offset and count
  *((volatile uint32_t *) 0x50500118) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50500798) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50900318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900598) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x0d801178; // Mask offset and count
  *((volatile uint32_t *) 0x50900118) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50900798) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50d00318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00598) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x0d801178; // Mask offset and count
  *((volatile uint32_t *) 0x50d00118) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d00798) = 0x00024000; // Post processing register

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010059c) = 0x00006920; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x11a01598; // Mask offset and count
  *((volatile uint32_t *) 0x5010011c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5010079c) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050059c) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x11a01598; // Mask offset and count
  *((volatile uint32_t *) 0x5050011c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5050079c) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090059c) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x11a01598; // Mask offset and count
  *((volatile uint32_t *) 0x5090011c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5090079c) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x0000003d; // Rows
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0059c) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x0001f811; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x11a01598; // Mask offset and count
  *((volatile uint32_t *) 0x50d0011c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d0079c) = 0x00024000; // Post processing register

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50100320) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003a0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x501005a0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100120) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007a0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50100720) = 0x0000ffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50500320) = 0x00009000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003a0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x505005a0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500120) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007a0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50500720) = 0x0000ffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50900320) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003a0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x509005a0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900120) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007a0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50900720) = 0x0000ffff; // Mask and processor enables

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50d00320) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003a0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d005a0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00120) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007a0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d00720) = 0x0000ffff; // Mask and processor enables

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x00017800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x024003b8; // Mask offset and count
  *((volatile uint32_t *) 0x50100124) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x00017800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x024003b8; // Mask offset and count
  *((volatile uint32_t *) 0x50500124) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x00017800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x024003b8; // Mask offset and count
  *((volatile uint32_t *) 0x50900124) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x0000003b; // Rows
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00524) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x00017800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x024003b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00124) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00724) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x00000039; // Rows
  *((volatile uint32_t *) 0x501001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x501002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a8) = 0x00006ba0; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x15c017b8; // Mask offset and count
  *((volatile uint32_t *) 0x50100128) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x00000039; // Rows
  *((volatile uint32_t *) 0x505001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x505002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x15c017b8; // Mask offset and count
  *((volatile uint32_t *) 0x50500128) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50500728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x00000039; // Rows
  *((volatile uint32_t *) 0x509001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x509002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x15c017b8; // Mask offset and count
  *((volatile uint32_t *) 0x50900128) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50900728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x00000039; // Rows
  *((volatile uint32_t *) 0x50d001a8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d002a8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00328) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x15c017b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00128) = 0x00001300; // 1D

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x0000001a; // Rows
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501004ac) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x5010052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ac) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x00017810; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x03c006b8; // Mask offset and count
  *((volatile uint32_t *) 0x5010012c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x0000001a; // Rows
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505004ac) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x5050052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x00017810; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x03c006b8; // Mask offset and count
  *((volatile uint32_t *) 0x5050012c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5050072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x0000001a; // Rows
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509004ac) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x5090052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x00017810; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x03c006b8; // Mask offset and count
  *((volatile uint32_t *) 0x5090012c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5090072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x0000001a; // Rows
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d004ac) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d0052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x00017810; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x03c006b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0012c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d0072c) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00000018; // Rows
  *((volatile uint32_t *) 0x501001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x501002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501004b0) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x501005b0) = 0x00006aa0; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x18001df8; // Mask offset and count
  *((volatile uint32_t *) 0x50100130) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00000018; // Rows
  *((volatile uint32_t *) 0x505001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x505002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505004b0) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x505005b0) = 0x00000aa0; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x18001df8; // Mask offset and count
  *((volatile uint32_t *) 0x50500130) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00000018; // Rows
  *((volatile uint32_t *) 0x509001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x509002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509004b0) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x509005b0) = 0x00000aa0; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x18001df8; // Mask offset and count
  *((volatile uint32_t *) 0x50900130) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50900730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00000018; // Rows
  *((volatile uint32_t *) 0x50d001b0) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d002b0) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d004b0) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x50d005b0) = 0x00000aa0; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x00017811; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x18001df8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00130) = 0x00001300; // 1D

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100034) = 0x00000009; // Rows
  *((volatile uint32_t *) 0x501001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x501002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b4) = 0x00006ba0; // Layer control
  *((volatile uint32_t *) 0x50100a34) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50100634) = 0x1e0021f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007b4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500034) = 0x00000009; // Rows
  *((volatile uint32_t *) 0x505001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x505002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b4) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50500a34) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50500634) = 0x1e0021f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007b4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900034) = 0x00000009; // Rows
  *((volatile uint32_t *) 0x509001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x509002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b4) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50900a34) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50900634) = 0x1e0021f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007b4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00034) = 0x00000009; // Rows
  *((volatile uint32_t *) 0x50d001b4) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d002b4) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00534) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b4) = 0x00000ba0; // Layer control
  *((volatile uint32_t *) 0x50d00a34) = 0x0001f801; // Layer control 2
  *((volatile uint32_t *) 0x50d00634) = 0x1e0021f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007b4) = 0x00022000; // Post processing register

  // Layer 10 quadrant 0
  *((volatile uint32_t *) 0x50100338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b8) = 0x0000e920; // Layer control
  *((volatile uint32_t *) 0x50100a38) = 0x0000a002; // Layer control 2
  *((volatile uint32_t *) 0x50100638) = 0x14401630; // Mask offset and count
  *((volatile uint32_t *) 0x50100138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007b8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 1
  *((volatile uint32_t *) 0x50500338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a38) = 0x0000a002; // Layer control 2
  *((volatile uint32_t *) 0x50500638) = 0x14401630; // Mask offset and count
  *((volatile uint32_t *) 0x50500138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007b8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 2
  *((volatile uint32_t *) 0x50900338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a38) = 0x0000a002; // Layer control 2
  *((volatile uint32_t *) 0x50900638) = 0x14401630; // Mask offset and count
  *((volatile uint32_t *) 0x50900138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007b8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 3
  *((volatile uint32_t *) 0x50d00338) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003b8) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a38) = 0x0000a002; // Layer control 2
  *((volatile uint32_t *) 0x50d00638) = 0x14401630; // Mask offset and count
  *((volatile uint32_t *) 0x50d00138) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007b8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00738) = 0xffffffff; // Mask and processor enables


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf32)
{
  uint16_t *out_buf = (uint16_t *) out_buf32;
  uint32_t val;
  volatile uint32_t *addr;
  int i;

  // Custom unload for this network, layer 10 (fc_MatMul_3): 8-bit data, shape: (21, 1, 1)
  addr = (volatile uint32_t *) 0x50404000;
  for (i = 0; i < 4; i++) {
    val = *addr;
    addr +=  0x2000;
    *out_buf++ = (int16_t)((val & 0xff)) << 5;
    *out_buf++ = (int16_t)(((val >> 8) & 0xff)) << 5;
    *out_buf++ = (int16_t)(((val >> 16) & 0xff)) << 5;
    *out_buf++ = (int16_t)(((val >> 24) & 0xff)) << 5;
  }
  addr = (volatile uint32_t *) 0x50804000;
  for (i = 0; i < 2; i++) {
    val = *addr;
    addr +=  0x2000;
    *out_buf++ = (int16_t)((val & 0xff)) << 5;
    *out_buf++ = (int16_t)(((val >> 8) & 0xff)) << 5;
    *out_buf++ = (int16_t)(((val >> 16) & 0xff)) << 5;
    *out_buf++ = (int16_t)(((val >> 24) & 0xff)) << 5;
  }

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

